-- Minimal Neovim configuration
vim.o.termguicolors = true

-- Enable syntax highlighting (defer some operations)
vim.cmd('syntax enable')
vim.cmd('filetype plugin indent on')

-- Set leader key
vim.g.mapleader = ' '
vim.g.maplocalleader = ' '

-- Set correct shell (use bash for terminal/yazi operations)
-- Use vim.fn.exepath to resolve the actual path, works on both Unix and Windows/MSYS
local bash_path = vim.fn.exepath('bash')
if bash_path ~= '' then
  vim.o.shell = bash_path
else
  vim.o.shell = 'bash'
end
vim.o.shellcmdflag = '-c'
if vim.fn.has('win32') == 1 then
  vim.o.shellquote = ''
  vim.o.shellxquote = ''
end

-- Clipboard integration
vim.opt.clipboard = 'unnamedplus'  -- Use system clipboard for all operations

-- Line numbers configuration
vim.opt.number = true
vim.opt.relativenumber = true

-- Buffer settings
vim.opt.hidden = true  -- Allow switching buffers without saving

-- Split direction
vim.opt.splitright = true
vim.opt.splitbelow = true

-- Terminal integration
require('terminal').setup()

-- Centralized keybind mappings
require('mappings').setup()

-- Keybind viewer
require('keybinds').setup()

-- Search functionality
require('search').setup()

-- Buffer line
require('bufferline').setup()

-- LSP configuration
require('lsp').setup()


-- Treesitter configuration
require('treesitter').setup()

-- Claude Code integration
require('claudecode-config').setup()

-- Build error integration
require('build-errors').setup()

-- Oil file explorer
require('oil-config').setup()

-- Colorscheme (generated by themix apply, may not exist on all machines)
local colors_dir = vim.fn.stdpath('config') .. '/colors'
local schemes = vim.fn.glob(colors_dir .. '/*.vim', false, true)
if #schemes > 0 then
  local name = vim.fn.fnamemodify(schemes[1], ':t:r')
  pcall(vim.cmd, 'colorscheme ' .. name)
end

-- Disable unused providers and features to reduce startup time
vim.g.loaded_perl_provider = 0
vim.g.loaded_ruby_provider = 0
-- vim.g.loaded_node_provider = 0  -- Re-enabled for Copilot
vim.g.loaded_python3_provider = 0  -- Disable if not using Python plugins

-- WSL2 performance optimizations
vim.opt.shadafile = "NONE"  -- Disable ShaDa to reduce WSL2 I/O overhead
vim.opt.swapfile = false  -- Disable swap files to prevent LSP rename conflicts

-- File change detection
vim.opt.autoread = true  -- Automatically reload files changed outside vim

-- Search settings
vim.opt.ignorecase = true  -- Case-insensitive search
vim.opt.smartcase = true   -- Unless you use uppercase

-- Write cwd to temp file on exit (for shell wrapper to pick up)
vim.api.nvim_create_autocmd('VimLeave', {
  callback = function()
    local cwd_file = vim.fn.expand('$TEMP/nvim-cwd.txt')
    local f = io.open(cwd_file, 'w')
    if f then
      f:write(vim.fn.getcwd())
      f:close()
    end
  end
})